### ISSUE TITLE
API KEY issue

### ISSUE THREAD

**Issue by RidhulKrishna** [RusAntr/currency_checking_app#2]
: Error: Error when reading 'lib/core/consts/api_key.dart': The system cannot find the file specified.
currency_repository.dart:3

import 'package:currency_checking_app/core/consts/api_key.dart';
       ^
: Error: Undefined name 'ApiKey'.
currency_repository.dart:9
  final _apiKey = ApiKey.getKey();
                  ^^^^^^

**Comment by RusAntr** [comment]
Hi! The api_key.dart file only contains a private API key, so I decided not to upload it to github. You can just use your own API key without creating this file or create a .dart file with the same name and put your own API key there.

The app uses API from "Abstract API". You can get your own API key at app.abstractapi.com
